//
//  ListForksModels.swift
//  DUGithubForks
//
//  Created by Di on 30.11.2017.
//  Copyright (c) 2017 Di. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListForks {
    // MARK: Use cases

    struct ForkDetails {
        var title: String
        var avatarURL: String
    }

    struct Fork {
        var details: ForkDetails
        var totalCount: Int
        var isSelectable: Bool
    }

    enum RepoHeader {
    struct Request {
    }
    struct Response {
        var repository: FetchedRepository
    }
    struct ViewModel {
        var details: ForkDetails
    }
    }
    enum FetchForks {
        struct Request {
            var forksCount: Int
        }
        struct Response {
            var repository: FetchedRepository?
            
            var errorMessage: String?
        }
        struct ViewModel {
            var forks: [Fork]
        }
    }

    enum SelectFork {
        struct Request {
            var forksCount: Int
            var index: Int
        }
        struct Response {
            var repository: FetchedRepository
        }
        struct ViewModel {
            var repository: FetchedRepository
        }
    }

}
