//
//  LoadForksPresenter.swift
//  DUGithubForks
//
//  Created by Di on 30.11.2017.
//  Copyright (c) 2017 Di. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoadForksPresentationLogic {
    func presentListForkes(response: LoadForks.FetchRepository.Response)
    func presentDefaultFieldValues(response: LoadForks.SetDefaultFields.Response)
}

class LoadForksPresenter: LoadForksPresentationLogic {
    weak var viewController: LoadForksDisplayLogic?

    // MARK: Handle Forks Response

    func presentListForkes(response: LoadForks.FetchRepository.Response) {
        let viewModel = LoadForks.FetchRepository.ViewModel(repository: response.repository, errorMessage: response.errorMessage)
        if response.isError {
            viewController?.displayError(viewModel: viewModel)
        } else {
            viewController?.displayForks(viewModel: viewModel)
        }
    }
    
    func presentDefaultFieldValues(response: LoadForks.SetDefaultFields.Response) {
        let viewModel = LoadForks.SetDefaultFields.ViewModel(fields: response.fields)
        viewController?.displayDefaultValues(viewModel: viewModel)
    }
}
