//
//  LoadForksModels.swift
//  DUGithubForks
//
//  Created by Di on 30.11.2017.
//  Copyright (c) 2017 Di. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LoadForks {
    // MARK: Use cases

    struct FormFieldes {
        var repoName: String
        var ownerName: String
    }

    enum FetchRepository {
        struct Request {
            var fields: FormFieldes
            var forksCount: Int
        }
        struct Response {
            var repository: FetchedRepository?
            var isError: Bool
            var errorMessage: String?
        }
        struct ViewModel {
            var repository: FetchedRepository?
            var errorMessage: String?
        }
    }
    
    enum SetDefaultFields {
        struct Request { }
        struct Response {
            var fields: FormFieldes
        }
        struct ViewModel {
            var fields: FormFieldes
        }
    }
}
